### ISSUE TITLE
Duplicated classes org.codehaus.plexus.util.xml.Xpp3Dom and org.codehaus.plexus.util.xml.Xpp3DomBuilder from maven-xml-impl

### ISSUE THREAD

**Issue by tmortagne** [codehaus-plexus/plexus-xml#17]
I just tried to upgrade to plexus-utils 4 which means adding plexus-xml as dependency here and there, but I had the surprise to notice that both plexus-xml and its direct dependency maven-xml-impl contain 2 classes with the same name and extremely similar code. I was wondering if this is really on purpose since it's not very clean.

I checked Xpp3Dom source and both versions seems very similar, the only changes I noticed are on the final static constants.

**Comment by elharo** [comment]
same package name too?

**Comment by tmortagne** [comment]
Yes, same package name too.

**Comment by elharo** [comment]
I don't see that in the maven-xml-impl  source code. Is it getting shaded into the jar somehow? Can you please post the command and output that leads you to believe that these classes are in maven-xml-impl?

**Comment by tmortagne** [comment]
> Can you please post the command and output that leads you to believe that these classes are in maven-xml-impl?

You can see that simply by opening the maven-xml-impl JAR from https://repo1.maven.org/maven2/org/apache/maven/maven-xml-impl/4.0.0-alpha-5/maven-xml-impl-4.0.0-alpha-5.jar for example.

**Comment by slachiewicz** [comment]
maven-xml-impl depends on plexus-xml that depends on maven-xml-impl - kind of circle

<img width="546" alt="image" src="https://github.com/codehaus-plexus/plexus-xml/assets/6705942/47c67c06-c738-4d86-9932-9342b8f4d08f">

**Comment by slachiewicz** [comment]
2nd Xpp3Dom come from transitive dependency to old plexus-utils 3.x
